import { randomUUID } from 'node:crypto';
export const defaultSettings={address:'À renseigner avant ouverture',timezone:'Europe/Paris',openingHours:{'0':[['11:00','23:00']],'1':[['11:00','23:00']],'2':[['11:00','23:00']],'3':[['11:00','23:00']],'4':[['11:00','23:00']],'5':[['11:00','23:00']],'6':[['11:00','23:00']]},acceptingOrders:false,deliveryEnabled:false,deliveryPostcodes:['13010'],deliveryRadius:0,minimumOrderCents:1500,deliveryFeeCents:250,voice:'marin',language:'fr',upsellEnabled:false,humanTransferNumber:'',greeting:'Bonjour et bienvenue chez Chicken World. Je suis votre assistant vocal IA. Que puis-je vous préparer ?',privacyNotice:'Vos propos sont transcrits pour traiter votre commande. Pour toute question, vous pouvez demander un membre du restaurant.',retentionDays:30};
const drink={id:'drink',name:'Boisson',min:1,max:1,options:['Coca','Coca Zero','Fanta','Ice Tea'].map((name,i)=>({id:['coca','coca-zero','fanta','ice-tea'][i],name,priceCents:0,available:true}))};
const sauce={id:'sauce',name:'Sauce',min:0,max:1,options:['BBQ','Algérienne','Samouraï'].map((name,i)=>({id:['bbq','algerienne','samourai'][i],name,priceCents:0,available:true}))};
const extra={id:'extras',name:'Suppléments',min:0,max:2,options:[{id:'cheese',name:'Fromage',priceCents:100,available:true},{id:'bacon',name:'Bacon',priceCents:150,available:true}]};
export const demoMenu=()=>[
 ['Burgers','Chicken Spicy',890,[sauce,extra]],['Burgers','Burger BBQ',990,[sauce,extra]],['Menus','Menu Chicken Spicy',1290,[drink,sauce,extra]],['Menus','Menu Burger BBQ',1390,[drink,sauce,extra]],['Wings','Wings x6',690,[sauce]],['Wings','Wings x12',1190,[sauce]],['Tenders','Tenders x3',590,[sauce]],['Tenders','Tenders x6',990,[sauce]],['Sides','Frites',350,[]],['Sides','Onion rings',450,[]],['Desserts','Cookie',290,[]],['Desserts','Tiramisu',450,[]],...['Coca','Coca Zero','Fanta','Ice Tea'].map(n=>['Drinks',n,250,[]])
].map(([category,name,price_cents,options])=>({id:randomUUID(),category,name,price_cents,available:true,options,ingredients:null}));
export async function seedMenu(db,restaurantId){for(const p of demoMenu()) await db.query('INSERT INTO products(id,restaurant_id,category,name,price_cents,options,ingredients) VALUES($1,$2,$3,$4,$5,$6,$7)',[p.id,restaurantId,p.category,p.name,p.price_cents,JSON.stringify(p.options),p.ingredients]);}
