import {z} from 'zod';
import {assert} from './domain.js';
export const customerSchema=z.object({name:z.string().max(120).optional(),phone:z.string().max(30).optional(),address:z.string().max(250).optional(),postcode:z.string().regex(/^\d{5}$/).optional(),instructions:z.string().max(500).optional()}).strict();
const id=z.string().uuid(),opts=z.array(z.string().max(80)).max(20),qty=z.number().int().min(1).max(30);
export const schemas={getRestaurant:z.object({}),getMenu:z.object({}),searchMenuItem:z.object({query:z.string().max(100)}),getProduct:z.object({productId:id}),getProductOptions:z.object({productId:id}),getCart:z.object({}),calculateCartTotal:z.object({}),addItemToCart:z.object({productId:id,quantity:qty,optionIds:opts}),updateCartItem:z.object({itemId:id,quantity:qty.optional(),productId:id.optional(),optionIds:opts.optional()}),removeCartItem:z.object({itemId:id}),setCustomer:z.object({customer:customerSchema,fulfillment:z.enum(['PICKUP','DELIVERY']).optional()}),checkDeliveryZone:z.object({postcode:z.string().regex(/^\d{5}$/)}),getDeliveryFee:z.object({}),prepareConfirmation:z.object({}),confirmOrder:z.object({quoteToken:id,confirmed:z.literal(true)}),transferToHuman:z.object({reason:z.string().max(250)})};
const descriptions={getRestaurant:'Informations et horaires autorisés.',getMenu:'Catalogue actuel : seuls produits, prix, options et disponibilités autorisés.',searchMenuItem:'Recherche dans le menu, aucun résultat veut dire produit absent.',getProduct:'Détail exact produit.',getProductOptions:'Groupes de choix, minima et maxima.',getCart:'Panier courant avec identifiants des lignes.',calculateCartTotal:'Seule source autorisée de prix total en centimes EUR.',addItemToCart:'Ajouter une ligne. Boissons différentes = lignes distinctes. Demander les choix obligatoires.',updateCartItem:'Remplacer la quantité ou la liste COMPLÈTE des options de cette ligne, pas un delta.',removeCartItem:'Supprimer une ligne précise.',setCustomer:'Renseigner client et retrait/livraison. Téléphone E.164 (+33).',checkDeliveryZone:'Vérifier code postal autorisé. Ne pas inventer un rayon.',getDeliveryFee:'Frais configurés.',prepareConfirmation:'Valider le panier complet et obtenir un récapitulatif à lire INTÉGRALEMENT. Puis attendre la réponse du client.',confirmOrder:'Créer la commande seulement après récapitulatif entendu et nouvelle confirmation orale claire du client. Idempotent.',transferToHuman:'Transférer au numéro configuré pour demande humaine, réclamation, allergie ou incompréhension.'};
export const toolDefinitions=Object.entries(schemas).map(([name,s])=>{const parameters=z.toJSONSchema(s);delete parameters.$schema;return {type:'function',name,description:descriptions[name],parameters};});
export async function runTool(service,ctx,name,raw,transfer=async()=>{throw new Error('Transfert non configuré');}){
 assert(schemas[name],'Outil inconnu');const args=schemas[name].strict().parse(raw);const t=ctx.restaurantId,c=ctx.cartId;
 if(name==='getRestaurant'){const r=await service.restaurant(t);return {name:r.name,...r.settings};}
 if(name==='getMenu')return service.menu(t);
 if(name==='searchMenuItem'){const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();return (await service.menu(t)).filter(p=>normalize(p.name).includes(normalize(args.query)));}
 if(name==='getProduct'||name==='getProductOptions'){const p=(await service.menu(t)).find(p=>p.id===args.productId);assert(p,'Produit inexistant');return name==='getProduct'?p:p.options;}
 if(name==='getCart'||name==='calculateCartTotal')return service.view(t,c);
 if(['addItemToCart','updateCartItem','removeCartItem','setCustomer'].includes(name))return service.mutate(t,c,name,args);
 if(name==='checkDeliveryZone'||name==='getDeliveryFee'){const {settings:s}=await service.restaurant(t);return {enabled:s.deliveryEnabled,eligible:name==='checkDeliveryZone'?s.deliveryEnabled&&s.deliveryPostcodes.includes(args.postcode):undefined,feeCents:s.deliveryFeeCents,minimumCents:s.minimumOrderCents};}
 if(name==='prepareConfirmation')return service.quote(t,c);
 if(name==='confirmOrder')return service.confirm(t,c,args,'voice');
 if(name==='transferToHuman')return transfer(args.reason);
}
