CREATE TABLE IF NOT EXISTS restaurants (
 id uuid PRIMARY KEY, name text NOT NULL, settings jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY, email text UNIQUE NOT NULL, password_hash text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS restaurant_users (restaurant_id uuid REFERENCES restaurants ON DELETE CASCADE, user_id uuid REFERENCES users ON DELETE CASCADE, role text NOT NULL CHECK(role IN ('OWNER','STAFF')), PRIMARY KEY(restaurant_id,user_id));
CREATE TABLE IF NOT EXISTS sessions (token_hash text PRIMARY KEY, user_id uuid REFERENCES users ON DELETE CASCADE, expires_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS phone_numbers (number text PRIMARY KEY, restaurant_id uuid NOT NULL REFERENCES restaurants ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS products (id uuid NOT NULL, restaurant_id uuid NOT NULL REFERENCES restaurants ON DELETE CASCADE, category text NOT NULL, name text NOT NULL, price_cents integer NOT NULL CHECK(price_cents>=0), available boolean NOT NULL DEFAULT true, options jsonb NOT NULL DEFAULT '[]', ingredients text, PRIMARY KEY(restaurant_id,id));
CREATE TABLE IF NOT EXISTS calls (id uuid PRIMARY KEY, restaurant_id uuid NOT NULL REFERENCES restaurants ON DELETE CASCADE, provider_sid text UNIQUE, caller text, started_at timestamptz NOT NULL DEFAULT now(), ended_at timestamptz, outcome text NOT NULL DEFAULT 'IN_PROGRESS', answered boolean NOT NULL DEFAULT false, transcript jsonb NOT NULL DEFAULT '[]', usage jsonb NOT NULL DEFAULT '{}', ai_cost_eur numeric, telephony_cost_eur numeric, UNIQUE(restaurant_id,id));
CREATE TABLE IF NOT EXISTS carts (id uuid PRIMARY KEY, restaurant_id uuid NOT NULL REFERENCES restaurants ON DELETE CASCADE, call_id uuid UNIQUE, version integer NOT NULL DEFAULT 0, data jsonb NOT NULL, quote_token text, quote_version integer, quoted_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(restaurant_id,call_id) REFERENCES calls(restaurant_id,id));
CREATE TABLE IF NOT EXISTS customers (id uuid PRIMARY KEY, restaurant_id uuid NOT NULL REFERENCES restaurants ON DELETE CASCADE, name text NOT NULL, phone text NOT NULL, UNIQUE(restaurant_id,phone));
CREATE TABLE IF NOT EXISTS orders (id uuid PRIMARY KEY, restaurant_id uuid NOT NULL REFERENCES restaurants ON DELETE CASCADE, cart_id uuid UNIQUE NOT NULL REFERENCES carts, call_id uuid, number bigint GENERATED ALWAYS AS IDENTITY, status text NOT NULL DEFAULT 'CONFIRMED' CHECK(status IN ('NEW','CONFIRMED','PREPARING','READY','COMPLETED','CANCELLED')), total_cents integer NOT NULL CHECK(total_cents>=0), snapshot jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(restaurant_id,call_id) REFERENCES calls(restaurant_id,id));
CREATE TABLE IF NOT EXISTS call_events (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, restaurant_id uuid NOT NULL REFERENCES restaurants ON DELETE CASCADE, call_id uuid, type text NOT NULL, data jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(restaurant_id,call_id) REFERENCES calls(restaurant_id,id));
CREATE TABLE IF NOT EXISTS tool_results (call_id uuid REFERENCES calls ON DELETE CASCADE, tool_call_id text NOT NULL, result jsonb NOT NULL, PRIMARY KEY(call_id,tool_call_id));
CREATE INDEX IF NOT EXISTS orders_tenant_time ON orders(restaurant_id,created_at DESC);
CREATE INDEX IF NOT EXISTS calls_tenant_time ON calls(restaurant_id,started_at DESC);
CREATE INDEX IF NOT EXISTS events_tenant_call ON call_events(restaurant_id,call_id,id);
